task:
  name: FrankaCubeStack
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:8192,${...num_envs}}
    envSpacing: 1.5
    episodeLength: 300
    enableDebugVis: false
    clipObservations: 5.0
    clipActions: 1.0
    startPositionNoise: 0.25
    startRotationNoise: 0.785
    frankaPositionNoise: 0.0
    frankaRotationNoise: 0.0
    frankaDofNoise: 0.0
    aggregateMode: 3
    actionScale: 1.0
    distRewardScale: 0.1
    liftRewardScale: 1.5
    alignRewardScale: 2.0
    stackRewardScale: 16.0
    controlType: osc
    asset:
      assetRoot: ../../assets
      assetFileNameFranka: urdf/franka_description/robots/franka_panda_gripper.urdf
    enableCameraSensors: false
  sim:
    dt: 0.01667
    substeps: 2
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 8
      num_velocity_iterations: 1
      contact_offset: 0.005
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 1000.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 1048576
      num_subscenes: ${....num_subscenes}
      contact_collection: 0
  task:
    randomize: false
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 256
        - 128
        - 64
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:FrankaCubeStack,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      ppo: true
      mixed_precision: false
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 1.0
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0005
      lr_schedule: adaptive
      schedule_type: standard
      kl_threshold: 0.008
      score_to_win: 10000
      max_epochs: ${resolve_default:10000,${....max_iterations}}
      save_best_after: 200
      save_frequency: 100
      print_stats: true
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 32
      minibatch_size: 16384
      mini_epochs: 5
      critic_coef: 4
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.0001
task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: ''
multi_gpu: false
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: isaacgymenvs
capture_video: false
capture_video_freq: 1464
capture_video_len: 100
force_render: true
headless: false
